### PR TITLE
Feature s2439 2

### PR DESCRIPTION
**Pull request by robertsv**

### CODE REVIEW

**Comment by ssinica** [comment]
@robertsv @tomsfeldmanis Just the note to think about. Probably we shouldn't use simple merge (or the merge from github UI) in such situations, when merge contains 3 commits with same description, but the change really is one. I think this situation would be perfect for "--squash" merge to master, because we don't really care about these 3 inner commits and it would be better and logical if in master we see it as one commit.

**Comment by tomsfeldmanis** [comment]
@ssinica @robertsv Agree. But what is the decision for cases when there are multiple separated commits with separate descriptions in a branch? Do we also do squashing or a simple merge?

**Comment by robertsv** [comment]
@ssinica - Is it possible to squash marge from git web. From cmd it is easy but will it recognize that pull request is completed?

**Comment by ssinica** [comment]
@robertsv @tomsfeldmanis If commits history is important then for sure we should do merging from github UI.

And if branch is merged via CLI, then we can close pull request manually. 

Or another option - we can rebase multiple commits in one and when merge them thru github UI. I think, this probably is the best idea. The  only challenge - we need to prepare branch before pull request. In that case it will always be possible to merge from github UI.

**Pull request merged**
