### PR TITLE
Feature s2439

### PR DESCRIPTION
**Pull request by robertsv**
@tomsfeldmanis - Please review!

### CODE REVIEW

**Comment by ssinica** [comment]
@robertsv Why my commits are in this pull request? Seems like something wrong with branch... Pls, make sure that only your changes and commits are in pull request.

**Comment by tomsfeldmanis** [comment]
@robertsv  Three code review notes:
$scope.getStreetName and $scope.getStreetNr: external service calls ($http.get) should be brought outside from the controller to a service method

$("#street-name").typeahead and $("#building-number").typeahead - direct DOM manipulations (like calling 'typeahead' function) should be brought outside to a directive

.loading { ... } the 'background' rule should be written into one line

**Comment by robertsv** [comment]
For some reason I am unable to merge this branch therefor I created second branch with cherry picked commits https://github.com/finansportalen/finansportalen2/tree/feature-S2439_2

**Comment by robertsv** [comment]
@tomsfeldmanis - As discussed - all remarks except first one are "implemented".

**Pull request closed without merging**
